apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-app
  template:
    metadata:
      labels:
        app: golang-app
    spec:
      containers:
        - name: golang-app
          image: meal-planning-and-grocery-management:latest
          ports:
            - containerPort: 8081
          # Add environment variables if needed
      # Add volume mounts, secrets, and other configurations if needed
